# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first_job: 
    runs-on: ubuntu-latest
    steps:
    - name: Print hello
      run: echo "Hello there"
    - name: print bye
      run: echo "Bye"
